//! Shared helpers for clone + snapshot/restore code paths.

use std::collections::HashMap;

use containerd_client::services::v1::{Container as ContainerProto, GetContainerRequest};
use containerd_client::tonic::Code;

use crate::client::Client;
use crate::consts::{BRIDGE_IP_LABEL, NETWORK_MODE_LABEL, PORT_BINDING_LABEL_PREFIX};
use crate::container::NetworkMode;
use crate::error::{Error, Result};
use crate::util::StatusExt;

/// Typed wrapper around containerd's `Container` proto. Centralises the
/// proto-to-typed mapping so callers don't reach into raw fields and miss
/// new ones added upstream.
#[derive(Debug, Clone)]
pub(crate) struct ContainerRecord(ContainerProto);

impl ContainerRecord {
    pub fn snapshotter(&self) -> &str {
        &self.0.snapshotter
    }
    pub fn snapshot_key(&self) -> &str {
        &self.0.snapshot_key
    }
    pub fn image(&self) -> &str {
        &self.0.image
    }
}

/// Errors with `ContainerNotFound` if `container_id` is missing.
pub(crate) async fn fetch_container_record(
    client: &Client,
    container_id: &str,
) -> Result<ContainerRecord> {
    let req = client.ns_req(GetContainerRequest {
        id: container_id.to_string(),
    });
    let container = client
        .containers_client()
        .get(req)
        .await
        .map_err(|e| {
            if e.code() == Code::NotFound {
                Error::ContainerNotFound(container_id.to_string())
            } else {
                e.into_crate_error("get_container")
            }
        })?
        .into_inner()
        .container
        .ok_or_else(|| Error::ContainerNotFound(container_id.to_string()))?;

    Ok(ContainerRecord(container))
}

pub(crate) fn network_from_labels(labels: &HashMap<String, String>) -> NetworkMode {
    match labels.get(NETWORK_MODE_LABEL).map(String::as_str) {
        Some("host") => NetworkMode::Host,
        _ => NetworkMode::Bridge,
    }
}

/// Managed labels are regenerated by `create_container`; never copy them.
pub(crate) fn is_managed_label(key: &str) -> bool {
    key == NETWORK_MODE_LABEL
        || key == BRIDGE_IP_LABEL
        || key.starts_with(PORT_BINDING_LABEL_PREFIX)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn network_defaults_to_bridge() {
        assert!(matches!(
            network_from_labels(&HashMap::new()),
            NetworkMode::Bridge
        ));
    }

    #[test]
    fn network_reads_host() {
        let mut l = HashMap::new();
        l.insert(NETWORK_MODE_LABEL.to_string(), "host".to_string());
        assert!(matches!(network_from_labels(&l), NetworkMode::Host));
    }

    #[test]
    fn network_unknown_falls_back_to_bridge() {
        let mut l = HashMap::new();
        l.insert(NETWORK_MODE_LABEL.to_string(), "isolated".to_string());
        assert!(matches!(network_from_labels(&l), NetworkMode::Bridge));
    }

    #[test]
    fn managed_label_recognises_known_keys() {
        assert!(is_managed_label(NETWORK_MODE_LABEL));
        assert!(is_managed_label(BRIDGE_IP_LABEL));
        assert!(is_managed_label(&format!(
            "{PORT_BINDING_LABEL_PREFIX}27017"
        )));
    }

    #[test]
    fn managed_label_passes_user_labels() {
        assert!(!is_managed_label("com.example.team"));
        assert!(!is_managed_label("atlas-local.deployment.name"));
        assert!(!is_managed_label("containerd-manager.snapshot.image"));
    }
}
